### ISSUE TITLE
Enable Page View Tracking

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckan-2.3#3]
Follow the simple steps described in http://docs.ckan.org/en/latest/maintaining/tracking.html#tracking to activate tracking of datasets which could be an useful addition to tracking user behaviour with https://github.com/ckan/ckanext-googleanalytics.
## Implementation would consist on
- [ ] Adding ckan.tracking_enabled = true on _production.ini_ config file
- [ ] Informing Proteus to update deployment scripts to include ckan.tracking_enabled = true
- [ ] Adapt https://github.com/OpenDevelopmentMekong/odm-deployment/blob/master/ansible/roles/ckan/tasks/main.yml so the variable is also set automatically while deploying dev/test environment.

**Comment by acorbi** [comment]
@chris-aeviator idea for enhancement
